{% set name = "arachne" %}
{% set version = "0.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/blinkseq/arachne/releases/download/{{ version }}/arachne.{{ version }}.tar.gz 
  sha256: 599960c3d4d88d0d180db23b5df96d64a47af46dca2441fa17d9d8e46212ee7d
build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('go') }}
    - go-licenses
    - make
  host:
    - zlib
    - libgomp
  run:
    - samtools >=1.23
    - minibwa >=0.7,<0.8

test:
  commands:
    - arachne --version

about:
  home: "https://github.com/blinkseq/arachne"
  summary: "Linked-Read Alignment Tool and successor to Lariat."
  description: |
    Arachne is a fork of Lariat that takes the best parts of lariat (speed, usability, not being C++)
    and marries it with the mapping performance of EMA. Because of this and other improvements and
    updates, Arachne output will be different from either Lariat or EMA output, presumably better.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - gominibwa/minibwa/LICENSE.txt
    - library_licenses/
  dev_url: "https://github.com/blinkseq/arachne"
  doc_url: "https://blinkseq.github.io/arachne"

extra:
  recipe-maintainers:
    - pdimens
  additional-platforms:
    - linux-aarch64
    - osx-arm64
